### ISSUE TITLE
关于具体实现

### ISSUE THREAD

**Issue by spiritwalking** [LLeavesG/BUPT-von-Neumann-CPUsimulation#1]
好像您的代码并不是完全按照CPU步骤进行的模拟，想请问一下在教师评价的时候有什么影响吗？

**Comment by LLeavesG** [comment]
可以说明一下具体是在哪里没按照CPU步骤进行模拟吗？我是按照课程实验要求做的，课程实验要求可能不是完全按照CPU步骤进行的模拟，但是是符合课程实验要求的，在OJ上评测也拿下了全AC。

**Comment by LLeavesG** [comment]
> 好像您的代码并不是完全按照CPU步骤进行的模拟，想请问一下在教师评价的时候有什么影响吗？

可以说明一下具体是在哪里没按照CPU步骤进行模拟吗？我是按照课程实验要求做的，课程实验要求可能不是完全按照CPU步骤进行的模拟，但是是符合课程实验要求的，在OJ上评测也拿下了全AC。

**Comment by spiritwalking** [comment]
> > 好像您的代码并不是完全按照CPU步骤进行的模拟，想请问一下在教师评价的时候有什么影响吗？
> 
> 可以说明一下具体是在哪里没按照CPU步骤进行模拟吗？我是按照课程实验要求做的，课程实验要求可能不是完全按照CPU步骤进行的模拟，但是是符合课程实验要求的，在OJ上评测也拿下了全AC。

比如说程序计数器与指令寄存器的使用，似乎不是从ir取指令，也不是跳转到pc执行，pc与ir只是数值上与cpu模拟情况相等，但是并没有像真正的CPU那样使用。

**Comment by LLeavesG** [comment]
> > > 好像您的代码并不是完全按照CPU步骤进行的模拟，想请问一下在教师评价的时候有什么影响吗？
> > 
> > 
> > 可以说明一下具体是在哪里没按照CPU步骤进行模拟吗？我是按照课程实验要求做的，课程实验要求可能不是完全按照CPU步骤进行的模拟，但是是符合课程实验要求的，在OJ上评测也拿下了全AC。
> 
> 比如说程序计数器与指令寄存器的使用，似乎不是从ir取指令，也不是跳转到pc执行，pc与ir只是数值上与cpu模拟情况相等，但是并没有像真正的CPU那样使用。

正如你所说，由于课程设计不合理，直到大一下学期大部分同学并不知道真正的CPU执行指令的实现过程，计导考虑此因素后简化了CPU模拟的实现，要求只需要按照实验说明给出即可。直到大二的CSAPP才让同学们理解了CPU的执行流程，但作为实验本身要求，这个方案是行得通的，并且在最后拿到了97的成绩，感谢你在此提出ISSUE。

**Comment by spiritwalking** [comment]
> > > > 好像您的代码并不是完全按照CPU步骤进行的模拟，想请问一下在教师评价的时候有什么影响吗？
> > > 
> > > 
> > > 可以说明一下具体是在哪里没按照CPU步骤进行模拟吗？我是按照课程实验要求做的，课程实验要求可能不是完全按照CPU步骤进行的模拟，但是是符合课程实验要求的，在OJ上评测也拿下了全AC。
> > 
> > 
> > 比如说程序计数器与指令寄存器的使用，似乎不是从ir取指令，也不是跳转到pc执行，pc与ir只是数值上与cpu模拟情况相等，但是并没有像真正的CPU那样使用。
> 
> 正如你所说，由于课程设计不合理，直到大一下学期大部分同学并不知道真正的CPU执行指令的实现过程，计导考虑此因素后简化了CPU模拟的实现，要求只需要按照实验说明给出即可。直到大二的CSAPP才让同学们理解了CPU的执行流程，但作为实验本身要求，这个方案是行得通的，并且在最后拿到了97的成绩，感谢你在此提出ISSUE。

了解了，感谢你的解答与开源代码提供的帮助！
